### ISSUE TITLE
Mock fails in a certain scenario

### ISSUE THREAD

**Issue by warvariuc** [Colin-b/pytest_httpx#118]
This code is based on https://github.com/Colin-b/pytest_httpx#reply-with-custom-body :
```python
def test_str_body(httpx_mock: HTTPXMock):
    httpx_mock.add_response(text="This is my UTF-8 content", status_code=httpx.codes.BAD_REQUEST)

    with httpx.Client(
        event_hooks={
            "response": [lambda response: response.raise_for_status()]
        }
    ) as client:
        try:
            client.get("https://test_url")
        except httpx.HTTPStatusError as exc:
            assert exc.response.text == "This is my UTF-8 content"
```
It fails with this error: 
```
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.
```

**Comment by Colin-b** [comment]
Hello @warvariuc ,

This is not related to pytest-httpx as this is httpx expected behavior (or a bug, idk tbh).
You can try it out without mocking, on a url that does not exists, you will have the exact same issue:

```python
import httpx

with httpx.Client(
        event_hooks={
            "response": [lambda response: response.raise_for_status()]
        }
) as client:
    try:
        client.get("https://github.com/thisdoesnotexists")
        print("np")
    except httpx.HTTPStatusError as exc:
        print(exc.response.text)

```

This will output the error you describe:

> Traceback (most recent call last):
>   line 9, in <module>
>    client.get("https://github.com/thisdoesnotexists")
>  \lib\site-packages\httpx\_client.py", line 1041, in get
>    return self.request(
>  \lib\site-packages\httpx\_client.py", line 814, in request
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
>  \lib\site-packages\httpx\_client.py", line 901, in send
>    response = self._send_handling_auth(
>  \lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
>    response = self._send_handling_redirects(
>  \lib\site-packages\httpx\_client.py", line 986, in _send_handling_redirects
>    raise exc
>  \lib\site-packages\httpx\_client.py", line 969, in _send_handling_redirects
>    hook(response)
>  line 5, in <lambda>
>    "response": [lambda response: response.raise_for_status()]
>  \lib\site-packages\httpx\_models.py", line 749, in raise_for_status
>    raise HTTPStatusError(message, request=request, response=self)
>httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://github.com/thisdoesnotexists'
>For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  line 12, in <module>
>    print(exc.response.text)
>  \lib\site-packages\httpx\_models.py", line 574, in text
>    content = self.content
>  \lib\site-packages\httpx\_models.py", line 568, in content
>    raise ResponseNotRead()
>httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

**Comment by warvariuc** [comment]
Thanks, Colin, for looking into this. I found these:
https://github.com/encode/httpx/discussions/1973
https://github.com/encode/httpx/discussions/2224
