### ISSUE TITLE
How can I send multiple responses matching the same request?

### ISSUE THREAD

**Issue by finswimmer** [Colin-b/pytest_httpx#119]
Hello,

thanks a lot for this project :pray: 

The only thing I miss until now, is an option to define a response list, like it exists for [requests-mock](https://requests-mock.readthedocs.io/en/latest/response.html#response-lists).

I need it to simulate a retry. Unlike in #75 my requests are identical, so unfortunately I have no header or something like that, which I can use to distinguish the requests.

fin swimmer

**Comment by finswimmer** [comment]
Using a callback which pops items from a list, seems to be a way to do it :thinking: 

```
responses = [
    httpx.Response(status_code=401),
    httpx.Response(status_code=200, content="some response"),
]

def response_list(_: httpx.Request) -> httpx.Response:
    return responses.pop(0)

httpx_mock.add_callback(response_list, method="POST", url=re.compile(".+/some/endpoint"))
```

**Comment by Colin-b** [comment]
Hello @finswimmer ,

You can call `httpx_mock.add_response` as many times as you want. As [explained in the documentation](https://github.com/Colin-b/pytest_httpx#how-response-is-selected), the order of registration will be respected.

Your sample could then be something like the following:

```python
httpx_mock.add_response(status_code=401, method="POST", url=re.compile(".+/some/endpoint"))
httpx_mock.add_response(status_code=200, content="some response", method="POST", url=re.compile(".+/some/endpoint"))
```

Does it solve your issue or did I miss something?

**Comment by finswimmer** [comment]
Awesome :+1:  Works perfectly fine :partying_face: 

(Now I have to go and buy some glasses to find it in the docs the next time :grin: )
