### ISSUE TITLE
Ability to fail a test case if unexpected requests are received and code is swallowing exceptions

### ISSUE THREAD

**Issue by ALSaleemALRaedah** [Colin-b/pytest_httpx#121]
Hello,

A Recent Scenario has required me to create a unit test in which two API calls are mock. One successful one with fake data and another that should cause the test to fail if called for business logic validation. Looking at the documentation I have noticed that its currently not supported. Is there any plans to add such feature?

Thanks.

**Comment by Colin-b** [comment]
Hello @ALSaleemALRaedah ,

Let me try to rephrase your issue to make sure I understand it properly as it can be interpreted in different ways:

1) You want to mock the response to a specific URL but this URL should be called only once. You want your test case to fail if it was called more than once. The approach for this check is to [assert that a single request was issued](https://github.com/Colin-b/pytest_httpx#check-sent-requests).

2) You want to mock a response to a specific URL but you want your test to fail if another URL is called. This is already the default behavior as [stated in the documentation](https://github.com/Colin-b/pytest_httpx#raising-exceptions). Unless your application code is swallowing exceptions, in which case you can still refer to 1) for a solution to this issue.

3) Something else that I did not understand. In which case could you provide more details (a test scenario maybe)?

Best Regards

**Comment by ALSaleemALRaedah** [comment]
Hello @Colin-b,

While scenario two will solve my case I'm not satisfied with it as a technical solution. The solution should be simple and direct if an endpoint is called test fails. No exception raising required. I shouldn't need to change my business logic to accommodate unit test exception handling.

 Best Regards

**Comment by ALSaleemALRaedah** [comment]
@Colin-b yeah this would solve my problem.

**Comment by Colin-b** [comment]
The next release will include the ability to toggle this on/off.
