### ISSUE TITLE
Consider exposing `HTTPXMock` for use outside of a pytest environment

### ISSUE THREAD

**Issue by cbensimon** [Colin-b/pytest_httpx#135]
Hi, thanks for you work and for providing this great tool in the httpx ecosystem

Would you (maintainers) be open to making things a bit more modular by offering the option to use `HTTPXMock` as a context manager?

Meaning we could still do exactly the same with the current fixture style

But we could also define the fixture ourselves (or use it outside of pytest) like :

``` python
@pytest.fixture
def api_mock(scope="whatever :)"):
    httpx_mock = HTTPXMock()
    httpx_mock.add_response(...)
    with httpx_mock:
        yield
```

Internally this would probably mean
- Moving the monkey patching inside `HTTPXMock.__enter__`
- Calling `self.reset`  inside `HTTPXMock.__exit__`
- Using HTTPXMock as a context manager in the `httpx_mock` fixture definition

Let me know what you think

**Comment by Colin-b** [comment]
Hello,

That is an interesting proposal. Could you elaborate on the use case? Is it to enable mocking only partially for a specific part of a larger test scenario ?

**Comment by bfontaine** [comment]
+1 for that. In my case I have several cases that rely on the same mocked routes, so it’s easier if I can use the same fixture in each test rather than re-defining all responses every time.

**Comment by mrswats** [comment]
This would also allow to mocked requests with different scopes. I am now in a similar situation. I have multiple tests mocking different requests, but when I run them all with randomized order, some of the time they fail because one request is mocked through one test and not the other and vice versa.

Unless I missed something in the docs, this is not currently supported, right?

**Comment by Colin-b** [comment]
> To me one use-case would be the ability to mock outside of Pytest :
> 
> If for instance I have a service A that depends on B, I'll mock B in my tests But then it's very handy to use this same (already existing) mocking in the development environment of the service A If `HTTPXMock` is only available as a pytest fixture then it's not possible
> 
> I currently already do this quite successfully with `requests` and `requests-mock` This particular point is my last blocker for transitioning to `httpx`

I don't see the full impact in term of additional maintaince for this change but I will look into it.

**Comment by Colin-b** [comment]
> This would also allow to mocked requests with different scopes. I am now in a similar situation. I have multiple tests mocking different requests, but when I run them all with randomized order, some of the time they fail because one request is mocked through one test and not the other and vice versa.
> 
> Unless I missed something in the docs, this is not currently supported, right?

Hello @mrswats Could you open a separate issue documenting your need? It's not clear to me and I feel like this is not related to the initial request here.

**Comment by mrswats** [comment]
@Colin-b It's the fact that when adding a request through the fixture, these are shared by all other tests using that same fixture. Being able to use what was suggested above would allow for creating independent fixtures outside the global scope.

**Comment by Colin-b** [comment]
Again, I don't think this is the appropriate place to discuss this as it is not related.
However fixtures in pytest have scopes. and `httpx_mock` one is the default (`function`). Meaning that every response you register will only apply for the duration of the test case. If you created fixtures relying on `httpx_mock` and adding responses, then of course using this fixture would mean using the registered responses.

This is the whole purpose of this package. I am not sure to see an issue here. If you mocked responses that should not be issued as responses to other requests, in the same test case, you can always use the available matchers to properly dispatch responses to the appropriate requests.

But again, this is a separate topic if you care to elaborate please open a dedicated issue.

Thanks again

**Comment by Colin-b** [comment]
Hello @cbensimon 

After quickly looking into it, we rely on existing pytest fixtures and this is a pytest plugin. So I cannot drop the pytest dependency or even the need for a pytest context.

However, if you still have a need for this, could you elaborate on what this would bring in the context of a pytest run?

Thanks again

**Comment by Colin-b** [comment]
Sadly  we won't invest into this. However feel free to fork this repository and remove everything that you don't need so that you could use it outside of pytest ! If you have something available on pypi at some point in the future let me know and I will gladly link it in the doc for some people that might have a need for this as well !
