### ISSUE TITLE
Can one add mocked responses *after* creating the HTTPX client?

### ISSUE THREAD

**Issue by bfontaine** [Colin-b/pytest_httpx#143]
Hello,
I’m getting the HTTPX client as a feature, so it’s already created by the time I mock responses:

```python
# conftest.py
@pytest.fixture(scope="function")
async def client(app):
    # ...

    async with AsyncClient(app=app, base_url="http://test") as c:
        yield c

# test file
async def test_foo(client, httpx_mock: HTTPXMock):
    httpx_mock.add_response(url="...", json={...})
    r = await client.get("/")
    assert r.json() == {...}
```

However this doesn’t seem to work; the test fails because the URL doesn’t match and the mocked response is never requested.

It works if I move the `add_response` inside the `client` fixture, just before the `async with`, but then the mock applies to _all_ tests and so fails in all but one because the mocked response is never requested.

Is there some way to make this work?

**Comment by Colin-b** [comment]
Can you try moving the `httpx_mock` fixture before `client` in the test signature, as in:

```python
# conftest.py
@pytest.fixture(scope="function")
async def client(app):
    # ...

    async with AsyncClient(app=app, base_url="http://test") as c:
        yield c

# test file
async def test_foo(httpx_mock, client):
    httpx_mock.add_response(url="...", json={...})
    r = await client.get("/")
    assert r.json() == {...}
```
