### ISSUE TITLE
Document how to configure options on the whole test suite

### ISSUE THREAD

**Issue by Apakottur** [Colin-b/pytest_httpx#154]
We are using the `assert_all_responses_were_requested` option in our test suite to avoid raising an error if not all responses were requested.
We have thousands of unit tests across hundreds of test files that would error without this flag being set to `False` so we were using the fixture to set it to false globally for the entire test suite.

The changes in https://github.com/Colin-b/pytest_httpx/pull/145 now make this flag scoped, which is a great feature, but not applicable in our case, meaning we can't use the newest version of the package.

It would be great to still be able to configure it once for the entire test suite (otherwise we'd have to add it to hundreds of files).

Or perhaps it's possible to configure it globally for entire test suite and I'm just missing something?

**Comment by Colin-b** [comment]
Hello @Apakottur ,

I am not proficient enough with pytest marks to give you a definitive answer on this.
Maybe @RazerM would know if such option exists?

If not, I am sure we could cook something up.

If you are using this option because you have a shared fixture registering a lot of responses that might not be useful in all tests, you could have a look at calling the following method at teardown (after the yield statement of your fixture).
```python
httpx_mock.reset()
```

This would however prevent any assertion performed at teardown by httpx_mock (on requests and responses).

**Comment by RazerM** [comment]
You could add this to your root `conftests.py` to add the marker to every test:

```python
def pytest_collection_modifyitems(session, config, items):
    for item in items:
        item.add_marker(pytest.mark.httpx_mock(assert_all_responses_were_requested=False))
```

**Comment by RazerM** [comment]
Also maybe we should change

https://github.com/Colin-b/pytest_httpx/blob/ca067b4adf0a13d20fc9f7ff816b97d584468040/pytest_httpx/__init__.py#L23

to use `request.node.iter_markers("httpx_mock")` so that we appropriately combine them, e.g.

```python
pytestmark = pytest.mark.httpx_mock(assert_all_responses_were_requested=False)

@pytest.mark.httpx_mock(non_mocked_hosts=["example.com"])
def test_foo():
    ...
```

**Comment by Colin-b** [comment]
Nice, so there is a workaround.

Indeed we should fix the way we currently handle provided options.
Feel free to draft a PR (or I'll do it whenever I find some more time :))

**Comment by Apakottur** [comment]
> You could add this to your root `conftests.py` to add the marker to every test:
> 
> ```python
> def pytest_collection_modifyitems(session, config, items):
>     for item in items:
>         item.add_marker(pytest.mark.httpx_mock(assert_all_responses_were_requested=False))
> ```

This works perfectly for our usecase, thank you!

**Comment by Colin-b** [comment]
Documentation was updated to help setting this up and code now handles multiple level of configuration
