### ISSUE TITLE
Deprecation warning of dependency

### ISSUE THREAD

**Issue by kjaymiller** [Colin-b/pytest_httpx#161]
I ran into an issue using this package with Python 3.13rc2

the issue was due to a deprecated configuration that will be removed in the new version. 

Here is the  error on 3.13

> WARNING: Ignoring version 0.21.1 of pytest-httpx since it has invalid metadata:
Requested pytest-httpx==0.21.1 from https://files.pythonhosted.org/packages/b6/c3/1d3634a2ff2f86458ea7974a7aa34b34d54e3a686c51c8d56d7abd21d226/pytest_httpx-0.21.1-py3-none-any.whl (from -r requirements.txt (line 74)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
>    pytest (<8.*,>=6.*)
>            ~~~^
> Please use pip<24.1 if you need to use this version.

When I tried this with 3.12 I get the following warning:

> DEPRECATION: pytest-httpx 0.21.1 has a non-standard dependency specifier pytest<8.*,>=6.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytest-httpx or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by Colin-b** [comment]
Hi, please use the latest version of pytest-httpx as we don't offer support for outdated versions.

This warning with python 3.13 (not yet released) was resolved since version 0.31.0, released on 2024-09-20

**Comment by kjaymiller** [comment]
apologies as I believe I had updated to the latest but that version had been pinned. Thank you.
