### ISSUE TITLE
Set cookies in the response

### ISSUE THREAD

**Issue by pawamoy** [Colin-b/pytest_httpx#19]
I don't think that feature exists yet?

I need to set a cookie in a response 🙂

**Comment by Colin-b** [comment]
Cookies are sent in headers, so I guess you can always try to [set the `Set-Cookie` header](https://github.com/Colin-b/pytest_httpx#reply-with-custom-headers) with [the value that you want](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) and see if this works (it should).

I am not familiar with cookies but you should be able to set the cookie `my_cookie` with value `my_value` using:

```python
headers={"Set-Cookie": "my_cookie=my_value"}
```

If this is not working or not easy enough we can maybe foresee the addition of an extra cookies parameters or some utility function converting [`httpx.Cookies`](https://www.python-httpx.org/api/#cookies) instance into the proper header.

Keep me updated :)

**Comment by pawamoy** [comment]
Right, thanks a lot! I'll try this tomorrow and report back :slightly_smiling_face:

**Comment by pawamoy** [comment]
It's working well with headers! Thanks again!
