### ISSUE TITLE
Question: How to mock only certain requests?

### ISSUE THREAD

**Issue by philwinder** [Colin-b/pytest_httpx#28]
Hi there,
Quick question. I'm using httpx for testing a webserver AND making external requests inside the webserver too.

I want requests to my webserver to go untouched. But I want to mock out all sub-requests made by my server.

Example:
Normal: http://testserver
Mocked: https://wikipedia...

I could inject, but I'm wondering if there is some functionality to disable mocking for certain urls. It seems like `httpx_mock` mocks everything.

Thanks in advance. 
Phil

**Comment by Colin-b** [comment]
Hi @philwinder 

Indeed this feature does not exists yet as the use case never occurred to me.

However it is possible to introduce it. Would the introduction of a fixture like the following be good enough for you?

```python
@pytest.fixture
def non_mocked_urls() -> list:
    return ["http://testserver"]
```

**Comment by Colin-b** [comment]
This fixture is now available. Refer to documentation if you want more details on how to use it.
