### ISSUE TITLE
Allow httpx > 0.17.x

### ISSUE THREAD

**Issue by fabaff** [Colin-b/pytest_httpx#35]
[`httpx-0-17.0`](https://github.com/encode/httpx/releases/tag/0.17.0) was released but at the moment only 0.16.x  is supported.

https://github.com/Colin-b/pytest_httpx/blob/6dddd90f469ca2064113778f97b5bc57cb838706/setup.py#L41

It would be nice to the version constrain could be updated. Thanks.

**Comment by Colin-b** [comment]
Fixed in release 0.11.0

**Comment by fabaff** [comment]
Thanks
