### ISSUE TITLE
async callback are not supported

### ISSUE THREAD

**Issue by mkotsalainen** [Colin-b/pytest_httpx#38]
When I register an async function as a callback to httpx_mock I get this error:
`TypeError: cannot unpack non-iterable coroutine object`

I suppose it's not awaited here:
https://github.com/Colin-b/pytest_httpx/blob/develop/pytest_httpx/_httpx_mock.py#L179

Is this a bug or am I using the library wrong?

Thanks!

**Comment by Colin-b** [comment]
Hello @mkotsalainen ,

The callback is not supposed to be async.
Is there a reason why you would need this?

Best Regards

**Comment by mkotsalainen** [comment]
Ok I see. I had test where I was concurrently doing some things via async.gather. One of them was a httpx call. My plan was to use asyncio.sleep in the mock response function. I could probably work around it by using normal sleep there instead. Thanks for a great util!

**Comment by Colin-b** [comment]
Sure, if the non-async way does not fit your use case do not hesitate to ask for a feature.

Thanks for the nice word :)

**Comment by Colin-b** [comment]
Hello @mkotsalainen, Release 0.21.1 is now available on pypi and allows you to register async callbacks.
