### ISSUE TITLE
Allow httpx to actually call certain routes

### ISSUE THREAD

**Issue by timothyjlaurent** [Colin-b/pytest_httpx#39]
I'm developing a FastAPI app that uses `async` route handlers. Because of this I'm using HTTPX as the test client as described here https://fastapi.tiangolo.com/advanced/async-tests/ . The app also uses httpx internally to call other endpoints.

When I tried to use the `httpx_mock` targeting just the external URLs, I noticed that it was also blocking the Test Client requests.

Is there some way to do this?

**Comment by Colin-b** [comment]
Does [this feature](https://github.com/Colin-b/pytest_httpx#do-not-mock-some-requests) solve your issue?

**Comment by Colin-b** [comment]
Does [this feature](https://github.com/Colin-b/pytest_httpx#do-not-mock-some-requests) solve your issue?

**Comment by Colin-b** [comment]
But in any case this might be something that should be handled properly without the need for this extra configuration. Please keep me updated on this :)

**Comment by timothyjlaurent** [comment]
You mean this was just _hiding_ on the top-level readme??  
Thanks for the kind direction, it works great!
