### ISSUE TITLE
Package for conda-forge

### ISSUE THREAD

**Issue by owenlamont** [Colin-b/pytest_httpx#42]
I love this package but was wondering if we could also have a conda version of it on [conda-forge](https://conda-forge.org/) as I work almost exclusively in conda environments and even though I can still pip install it there upgrades would work more smoothly if pytest_httpx was available as a conda package too.

The [process to create - and maintain - a package on conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html) is relatively easy and straight-forward for pure Python pip packages. Happy to help with this if you're open to the idea. From a quick check of the dependencies these all appear to available on conda-forge too so I don't anticipate any problems there.

**Comment by Colin-b** [comment]
Glad to hear that you love this package. Sure, feel free to come up with a pull request, or else I will check what I can do (but I can already tell you I wont have time to do it myself until a few weeks, I can review and validate PR tough ;))

**Comment by owenlamont** [comment]
That's fine - happy to work on it myself if you're good with that. No PR here required - conda-forge packages are managed in their own repo setup by the conda-forge team which is pretty minimal (it just links back to the latest GitHub or PyPi release).

**Comment by Colin-b** [comment]
I am absolutely fine with that :)

**Comment by owenlamont** [comment]
Sorry let this slip a while but finally raised a PR with conda-forge to create a conda version [here](https://github.com/conda-forge/staged-recipes/pull/15594). I put myself as the only maintainer for now - happy to add you @Colin-b if you want to keep an eye on it too.

Conda-forge packages are fairly automatic - when they detect the PyPi package has updated they will generate a new PR automatically to re-sync - so unless dependencies change you can normally just approve that PR.

We'll need to wait to see when one of the conda-forge team approves the above PR - when they do a new repo should be created - something like github.com/conda-forge/pytest-httpx-feedstock which is where the conda recipe will live.

**Comment by owenlamont** [comment]
Conda-forge package is up in this [GitHub repo here](https://github.com/conda-forge/pytest-httpx-feedstock) 

It can be installed with:

```console
conda install pytest-httpx -c conda-forge
```

Closing this issue now.
