### ISSUE TITLE
How do simulate multiple responses, similar to `side_effect` in mock?

### ISSUE THREAD

**Issue by EdLeafe** [Colin-b/pytest_httpx#75]
I have a method where if a call received a `401` response, it then calls the auth API to refresh its auth token, and then re-issue the call with the new token. When done synchronously with `requests`, I can mock out the call with multiple responses in the `side_effect` parameter.

Moving to `httpx` and async calls, I'm stumped how to test this case. I tried adding multiple `httpx_mock.add_reponse()` calls, but of course that didn't work. Any advice?

**Comment by EdLeafe** [comment]
Thanks for the ad, but we're using an internal auth system. 😁

The system caches auth tokens which expire after a period of time. So the general flow is this:

```
async def call_api(...):
    try:
       await make_request(<args with cached token>)
    except Unauthorized:
       new_token = get_new_token()
       await make_request(<args with new token>)
```

To test this case there are 3 async calls needed: failed auth, new token, succeed. How can I test the `call_api()` method with httpx?

**Comment by Colin-b** [comment]
You can [match on headers](https://github.com/Colin-b/pytest_httpx#matching-on-http-headers), so I would do something along this line (assuming you send your token in the standard way):

```python
def test_new_token_is_used_when_token_is_expired(httpx_mock):
    # Mock request with expired token response
    httpx_mock.add_response(match_headers={'Authorization': 'Bearer EXPIRED_TOKEN'}, status_code=401)
    # Mock new token response
    httpx_mock.add_response(url="AUTH_URL", json={"token": "NEW_TOKEN"})
    # Mock request with new token response
    httpx_mock.add_response(match_headers={'Authorization': 'Bearer NEW_TOKEN'})
```

Of course you have to return the proper body and filter on the proper information but that's the spirit. All those information can be found [in the documentation](https://github.com/Colin-b/pytest_httpx/blob/develop/README.md#add-responses).

Don't hesitate to ask if something is not clear. Always a good opportunity to clean up documentation.

**Comment by EdLeafe** [comment]
ok, I think I understand. I guess that I wasn't using matching correctly. Thanks for the help!
