### ISSUE TITLE
Add param to disable verify over non-requested mock.

### ISSUE THREAD

**Issue by Bernardoow** [Colin-b/pytest_httpx#77]
I had a scenario where I wanted to all request to be verified about over non-request, but just ONE request I wanted to be free verification.

With this new feature I can achieve this logic.

I created this PR #76.

**Comment by Colin-b** [comment]
Hello @evbo,

That is not what this request is about.
Could you elaborate your need in a separate issue please?

Thanks :)

**Comment by Colin-b** [comment]
As explained in the pull request, #137 should address this is a clean way.
