### ISSUE TITLE
Update to httpx 0.23.0

### ISSUE THREAD

**Issue by davidmreed** [Colin-b/pytest_httpx#79]
httpx released [version 0.23.0](https://github.com/encode/httpx/releases/tag/0.23.0) this morning, which corrects a significant security issue. It also removes support for Python 3.6.

I'd like to update my projects to use the new version alongside pytest_httpx. Could the project update its dependency, or would you welcome a PR to make that change?

**Comment by Colin-b** [comment]
Thanks to @shirblc , release 0.21.0 is now available on pypi
