### ISSUE TITLE
Async callbacks should be allowed to delay some responses while not blocking the async loop

### ISSUE THREAD

**Issue by citrusLover** [Colin-b/pytest_httpx#85]
Hi,

For a project that makes a lot of async requests I would like to emulate the effect of slow http responses. AFAIK that is currently not supported in this library. To me it would be useful to have an option to specify a delay in (micro)seconds.

I would be happy to provide a PR if this is something you would consider merging.

Cheers

**Comment by Colin-b** [comment]
That's one of the purpose of the dynamic response: https://github.com/Colin-b/pytest_httpx#dynamic-responses :)

**Comment by citrusLover** [comment]
I'm not sure if that will work because the callback is always sync, there is no async callback right?
So lets say that I'm making async 2 responses, one directly after the other. The first one I want to delay with 0.5sec and the second one without delay. Doing a sleep in the sync callback will delay both responses

**Comment by Colin-b** [comment]
Indeed, you would have to use [asyncio.sleep](https://docs.python.org/3/library/asyncio-task.html#asyncio.sleep) but as callbacks are not async, you can't. #38 and #43 did had the same requirement but managed to do it without async callbacks. Just to make sure, can you confirm that time.sleep is blocking the asyncio loop?

**Comment by Colin-b** [comment]
I do agree, I was hoping for some low hanging fruit in case my understanding of async was incorrect ;)

I have already an implementation idea in mind, basically I would like to not change anything from your perspective, except that add_callback would accept async functions. I think that's achievable with minor impact on code base (I hope so anyway). However It will involve a bunch of new test cases , so i'll put it in my backlog.

I hope to find some time to dig into this soon enough

**Comment by Colin-b** [comment]
Release 0.21.1 is now available on pypi and allows you to register async callbacks. You can also find a sample in documentation registering an async callback simulating network latency.

**Comment by citrusLover** [comment]
Thanks a lot Colin! Really appreciate the fast responses and merge of the new functionality. Thanks for maintaining this package :)
