### ISSUE TITLE
If the url query parameter contains Chinese characters, it will cause an encoding error

### ISSUE THREAD

**Issue by uncle-shu** [Colin-b/pytest_httpx#87]
```
httpx_mock.add_response(
      url='test_url?query_type=数据',
      method='GET',
      json={'result': 'ok'}
 )
```
Executing the above code, It wil cause an encoding error:

> obj = '数据', encoding = 'ascii', errors = 'strict'
> 
>     def _encode_result(obj, encoding=_implicit_encoding,
>                             errors=_implicit_errors):
>        return obj.encode(encoding, errors)
> E       UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
> 
> /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/parse.py:108: UnicodeEncodeError

**Comment by Colin-b** [comment]
Thanks for reporting.

**Comment by Colin-b** [comment]
Release 0.21.2 fixing this issue is now available on pypi.
