### ISSUE TITLE
Consider adding more request matchers

### ISSUE THREAD

**Issue by Bernardoow** [Colin-b/pytest_httpx#96]
Hi !!

It is possible to match request attributes? These attributes are timeout, auth, and others. 
I'm trying to use this to ensure that the request has these attributes.

At the documentation has headers, methods, and content. Can we develop new feature?

**Comment by Colin-b** [comment]
Closed as no response was received on this. If you want to assert a specific request attribute, please open and provide the type of attribute and the type of values it should allowed to be matched against.
